### ISSUE TITLE
No documentation on how to run this

### ISSUE THREAD

**Issue by lukasz-pekala** [paulomenezes/warcraft-js#1]
Can you please provide information on how to run this?
Any steps required? Looks like it needs to be run under node.js but no dependencies were defined in package.json

**Comment by paulomenezes** [comment]
@lukasz-pekala this project was stopped and I finished the game in C# with monogame: https://github.com/paulomenezes/warcraft-monogame

But this project was running under nwjs, you need to run `nw .` in main folder
